defmodule Playground.Support.RawTicket do
  use Ash.Resource,
    data_layer: AshPostgres.DataLayer

  postgres do
    table "tickets"
    repo Playground.Repo
  end

  actions do
    defaults [:read, :update]

    read :archived do
      filter expr(not is_nil(archived_at))
    end
  end

  attributes do
    # Add an autogenerated UUID primary key called `:id`.
    uuid_primary_key :id

    # Add a string type attribute called `:subject`
    attribute :subject, :string do
      allow_nil? false
    end

    attribute :status, :atom do
      constraints one_of: [:open, :closed]
      default :open
      allow_nil? false
    end

    attribute :archived_at, :utc_datetime_usec
  end

  relationships do
    belongs_to :representative, Playground.Support.Representative
  end

  code_interface do
    define_for Playground.Support
    define :archived
  end
end
